# Generated by Django 4.0.3 on 2022-03-31 01:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloglandingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='pilcrow', template='streams/content/rich_text.html')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='pilcrow', template='streams/content/markdown.html')), ('h1', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h1.html')), ('h2', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h2.html')), ('h3', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h3.html')), ('h4', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h4.html')), ('h5', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h5.html')), ('h6', wagtail.core.blocks.CharBlock(icon='title', template='streams/content/h6.html')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', template='streams/content/content/image.html'))], default=''),
            preserve_default=False,
        ),
    ]
