# Generated by Django 4.0.3 on 2022-04-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_content_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview_text',
            field=models.CharField(default='Test', max_length=150),
            preserve_default=False,
        ),
    ]
